package dam2.ejemploHibernate;
// Generated 15 ene 2024 21:04:16 by Hibernate Tools 6.3.1.Final

/**
 * Productos generated by hbm2java
 */
public class Productos implements java.io.Serializable {

	private ProductosId id;

	public Productos() {
	}

	public Productos(ProductosId id) {
		this.id = id;
	}

	public ProductosId getId() {
		return this.id;
	}

	public void setId(ProductosId id) {
		this.id = id;
	}

}
